### ISSUE TITLE
Funds not showing in the Electrum-raven app

### ISSUE THREAD

**Issue by Groucho1** [standard-error/electrum-raven#11]
Hi, 
I've set up the Electrum-raven Ledger wallet. I've sent 10 RVN as a test from Raven soft Mobile wallet to the new ledger wallet but the funds don't show in the Electrum-Raven app and haven't appeared. in the "Coins" tab
I've checked the address and its correct and  I scanned the Q code and they have left the mobile wallet but they're not showing in the Electrum wallet? any ideas?
The wallet does say "Not connected" but not sure what that really means.

Thanks

**Comment by standard-error** [comment]
Electrum-raven needs to connect to a server to verify the block headers and get your transaction history. For some reason it appears you can't connect. The debug log (tools -> log viewer) may have more information on why this is.

The default server is the one I run at electrumx-rvn.nbits.dev. This is up and running, and publicly accessible as far as I know. You could try a different one (tools -> network), though I'm not sure anyone else has made a server available. Or run a personal server, using https://github.com/standard-error/electrum-personal-server/releases

**Comment by Groucho1** [comment]
Thanks mate. changing the network address worked.

Appreciate your help!
