### ISSUE TITLE
Server Not connecting

### ISSUE THREAD

**Issue by fahid1** [standard-error/electrum-raven#12]
Hi my wallet is not connecting to server. It just suddenly stopped working after a transection.
I  re-downloaded the wallet but still it's not connecting.

**Comment by standard-error** [comment]
This isn't an issue with the electrum-raven client itself but is caused by a lack of public servers. I'd recommend using EPS instead for your server https://github.com/standard-error/electrum-personal-server as this is far better for privacy and other reasons
