### ISSUE TITLE
On May 7, Ravencoin KAWPOW fork was successfully completed. Since then I have not been able to check my balance at the Electrum Wallet.

### ISSUE THREAD

**Issue by topcys** [standard-error/electrum-raven#13]
On May 7, Ravencoin KAWPOW fork was successfully completed. Since then I have not been able to check my balance at the Electrum Wallet.

**Comment by standard-error** [comment]
RVN hard forked on May 7 and the changes are incompatible with Electrum-RVN 3.3.8-2. An update is being worked on but I don't have an ETA. In the meantime if you need urgent access to the funds I recommend using an alternative:
Chaintek wallet (works with ledger RVN app) https://wallet.chaintek.net/
If all else fails you can recover your private keys from the seed words but I really don't recommend this unless you can't wait. https://iancoleman.io/bip39/

**Comment by topcys** [comment]
I was a bit relieved at your response. And I want you to work a little harder to use my Electrum Wallet. Thank you.

**Comment by mailosss** [comment]
I warmly welcome ! Is it known when electrum 3.3.8 will work? My wallet with RVN still does not connect ... Please reply.

**Comment by pimvdmolen** [comment]
@standard-error do you have an ETA? I also still can't connect my wallet to any server.
