### ISSUE TITLE
typo in payment uri

### ISSUE THREAD

**Issue by ivo1981** [standard-error/electrum-raven#6]
When you try to receive a payment the uri in the QR looks like this: "Ravencoin:<address>" the mobile wallet is unable to scan the QR. 
The correct uri is "raven:<address>" the mobile wallet is unable to scan the QR

**Comment by standard-error** [comment]
Thanks for report. This should be fixed in [3.3.8pre2](https://github.com/standard-error/electrum-raven/releases/tag/3.3.8pre2). Please reopen issue if not.
